DROP DATABASE IF EXISTS NaveTeste;

CREATE DATABASE NaveTeste;

USE NaveTeste;

CREATE TABLE POSTS (
ID              INT NOT NULL,
AUTHOR        	VARCHAR(15) NOT NULL,
TITLE		VARCHAR(15) NOT NULL,
TEXT_		VARCHAR(40) NOT NULL,
CREATED_AT	TIMESTAMP NOT NULL,
UPDATED_AT	TIMESTAMP NOT NULL
);

CREATE TABLE COMMENTS(
ID              INT NOT NULL,
POST_ID        	INT NOT NULL,
MESSAGE		VARCHAR(40) NOT NULL,
AUTHOR		VARCHAR(15) NOT NULL,
CREATED_AT      TIMESTAMP NOT NULL,
UPDATED_AT      TIMESTAMP NOT NULL
);

ALTER TABLE POSTS ADD PRIMARY KEY (ID);
ALTER TABLE COMMENTS ADD PRIMARY KEY (ID);
ALTER TABLE COMMENTS ADD FOREIGN KEY(POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE;


 
